app = "bookstore-still-feather-4847"
primary_region = "gru"

# Comando para abrir o shell do Django se necessário
console_command = "python manage.py shell"

[build]
  # Usa o Dockerfile no mesmo diretório do projeto
  dockerfile = "Dockerfile"

[deploy]
  # Executa migrações automaticamente após deploy
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8080"
  DJANGO_ALLOWED_HOSTS = "bookstore-still-feather-4847.fly.dev"
  SECRET_KEY = "R0oHkQlrWpr8ihYsI5gIqz5n5pAwVE25JxqaEk2MRkGEfXjP0D"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
