# fly.toml - Configuração para Django no Fly.io
app = "bookstore-still-feather-4847"
primary_region = "gru"

# Comando para abrir o shell do Django se necessário
console_command = "python manage.py shell"

[build]
  # Usa Dockerfile na raiz
  dockerfile = "Dockerfile"

[deploy]
  # Executa migrações automaticamente após deploy
  release_command = "python manage.py migrate --noinput"

[env]
  # Fly recomenda 8080 como porta interna
  PORT = "8080"
  DJANGO_ALLOWED_HOSTS = "bookstore-still-feather-4847.fly.dev"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  # Caminho interno para os static files coletados pelo Django
  guest_path = "/code/static"
<<<<<<< HEAD
  url_prefix = "/static/"
=======
  url_prefix = "/static/"
>>>>>>> 94eb6fd2039fdadd0b769f037aff2dc07de085ab
