name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 7_django_framework/bookstore  # subdiretório do projeto Django

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: flyctl deploy --remote-only --app bookstore-still-feather-4847 --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
