name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bookstore

    env:
      DEBUG: "0"
      SECRET_KEY: "testsecret"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      SQL_ENGINE: "django.db.backends.sqlite3"
      SQL_DATABASE: "test_db.sqlite3"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run python manage.py test

      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
